### ISSUE TITLE
Refactor StorageAccess

### ISSUE THREAD

**Issue by romac** [TarsierMessenger/TarsierMessenger#72]
- [x] ~~#87~~ Move stuff around
- [x] ~~#87~~ Add a UserRepository
- [x] ~~#87~~ Add UserPreferences class.
- [x] ~~#87~~ Replace usage of StorageAccess with UserPreferences in HomeActivity and ProfileActivity.
- [x] ~~#92~~ Complete `ChatRepository`
- [x] ~~#93~~ Implement `PeerRepository`
- [x] ~~#94~~ Implement `MessageRepository`
